### ISSUE TITLE
low resolution output

### ISSUE THREAD

**Issue by shaishaicookie** [TIGER-AI-Lab/ConsistI2V#17]
Firstly, excellent work. Consistency with the first frame is very important in the actual image animation generation. I play with ConsistI2V on Replicate with different images. However, the image animation has a low-resolution issue. The input images are high-resolution, but the output video is in low resolution. Even the demo outputs on Replicate have low resolution. 
	1.	What are the prompt settings for these outputs of video gallery on the project page?
	2.	Is the low resolution related to the prompt settings, or is it a limitation of the model itself?
<img width="1031" alt="Screenshot 2024-05-23 at 4 00 58 PM" src="https://github.com/TIGER-AI-Lab/ConsistI2V/assets/85833278/60a3a103-3c1e-4f16-ad1f-d67da0c5e9a1">
<img width="653" alt="Screenshot 2024-05-23 at 4 05 07 PM" src="https://github.com/TIGER-AI-Lab/ConsistI2V/assets/85833278/3fb5b23c-dd3e-4bc2-aaf8-819737ea9b18">
Again, thank you for your excellent work.

**Comment by wren93** [comment]
Hi, for prompt settings, you can check out figure 9 and 10 in the paper.

The low resolution issue is because the training resolution is low. It's not related to the prompt. Please check out our huggingface demo (https://huggingface.co/spaces/TIGER-Lab/ConsistI2V) and you can select different resolutions there (although the quality of directly generating higher resolution videos might not be guaranteed). We are working on training a higher resolution model at the moment.
